### PR TITLE
Fixes for compat with Nim 0.19.0+.

### PR DESCRIPTION
**Pull request by dom96**
This is rough because Ludum Dare :)

I couldn't get the .gitignore to work so I just deleted it. Help welcome.

### CODE REVIEW

**Comment by oprypin** [comment]
Thanks.

Please don't touch the gitignore :o

And since you're changing the generated files, presumably the generator should change as well.
Maybe I can help with that.

**Comment by dom96** [comment]
While you're at it, add some big warnings telling silly people like me not to edit the generated files :)

**Comment by oprypin** [comment]
Please just exclude gitignore from the commit, I'll fix the rest.
You can always use `--force`, but I think now that you have it added you won't even need that.

**Comment by dom96** [comment]
Busy with LD right now. But I can do it later, feel free to commandeer this PR if you don't feel like waiting

**Pull request merged**
